### ISSUE TITLE
Blockchain Download

### ISSUE THREAD

**Issue by Vortex20000** [MetaServe/Satoshis#24]
Does not download blockchain.spv. Stuck at 600+ KB file size.

**Comment by trismegistis** [comment]
How is it against the EULA? You aren't selling currency. The player's already have currency they just move it in and out

**Comment by meta1203** [comment]
From http://www.minecraftforum.net/news/59832-new-eula-now-in-effect

>What do you mean by “hard currency” compared to “soft currency”?

>Hard currency is real money or anything that can be converted into real money, including Bitcoins. Soft currency is available in-game only, and has no real-world value. The restrictions in the EULA only apply to hard currency; you may unlock things in-game with soft currency.

Although, last I heard, there isn't really any enforcement of the EULA going on...

**Comment by trismegistis** [comment]
It's true, but this plugin doesn't work lol
